### ISSUE TITLE
望月さんのOnboarding Day 1 Checklist【本人】

### ISSUE THREAD

**Issue by Khamida-schemeverge** [scheme-verge-inc/Onboarding#1]
**👋scheme verge Onboardingへようこそ！👋**
まず、scheme verge のOnboardingの大まかな流れを[こちらのタイムライン](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)から確認しましょう。アサインされたのチェックリストとチェックリストの締め切りに従って、Onboardingを進めてください。

Onboardingの流れ

①招待通知
@schemeverge.com メールから通知が来たら、URLを踏んでscheme verge onboardingを見えるようになります。
②アクセス方法
scheme verge inc →Onboarding → Projects → scheme verge onboarding。
scheme verge onboarding プロジェクトを開いたら、今後より簡単なアクセスをできるようにこのページをブックマークとして保存してください。
③自分に割り当てられたタスクを確認してください。
④タスクに取り組み始めたら、[to-do] から [in progress] に移動することを忘れないでください。
⑤onboardingのどの部分にいるかに応じてタスクを開き、完了するまでタスクのチェックを開始してください。 リスト上のすべてのタスクが終了したら、[閉じる] を押します。他にタスクの進捗を報告する必要はありません。

❗️質問やコメントがある場合は、@[khamida.malianchinova@schemeverge.com](mailto:khamida.malianchinova@schemeverge.com) をメンションするタスク フィールドの下にコメントしてください。
❗️誤りや提案を見つけた場合は、Slack でご連絡ください。Onboardingを進めて、以下のto-doを完了させましょう。

**完了したら右のチェックボックストにチェックを入れてください。**

- [x] [Handbook](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)の使い方を確認しよう
- [x]  [Handbook](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)の検索をしよう
- [x]  Google Driveに[scheme_verge_all]フォルダを追加しよう

**Slackを使いこなそう**
プロフィールを設定しよう

- [x] プロフィール写真をアップロードしよう
- [x] timesを作成しよう
- [x] timesにコーポレートメンバーと部門メンバーを追加しよう
- [x] ppl_noticeに挨拶を投稿しよう
- [x] 気になるtimes・サークルチャンネルに参加してみよう
- [x] GitHubとSlackの連携しよう

    
- [x] AHMの直近過去2回分を視聴しよう
- [x] AHMと懇親会の参加をカレンダーで返事しよう

**カレンダーを使いこなそう**

- [x] 予定をセットし、__さんをインバイトしよう
- [x]  稼働時間を表記しよう
- [x] キャンセル・リスケしてみよう
- [x] Onboarding最初週、最初月のヒアリング招待を確認しよう
- [x] 他の人のカレンダーを見れるように設定しましょう
- [x] Googleカレンダーの予定を他の人でも変更/編集できるように設定しよう
- [x] [よくコミュニケーションするそうメンバーのスケジュールを見るように設定しましょう]((https://www.infact1.co.jp/staff_blog/webmarketing/47276/)    )
- [x] 田中さん・志方さんのカレンダーの使い方を確認しましょう。
- [x] zoomの設定方法を確認しましょう。
- [x] メール署名の設定をしよう

- [x] [こちらのスプシ](https://docs.google.com/spreadsheets/u/0/d/1G0dgMSk-ZZQG9NtNtLzveC7VM_8PeWUjCUUs3ocRJ08/edit)に名前とメールアドレスを入力しよう
**A欄に入力不要です**
- [x] HubSpotの招待を確認しよう
- [x] [Handbookの写真・スキルと趣味は入れてるかどうか確認](https://sites.google.com/d/1_j7rQcBhk5MY8LqCSX3pigOaxA727oEM/p/1S7-0ZayS_S_wrpldnFOWzHuA1uYkUbnn/edit)
- [x] Facebookアカウントを作成しよう 
**※Facebookの[2段階認証はセキュリティ](https://ja-jp.facebook.com/help/148233965247823)上必須設定にしてください。**
- [x] 開発環境のHoraiをダウンロードしよう
- [x] スマホにmessengerをインストールし、使い来なそう
- [x] PCのスペックについて確認
- [x] 情報セキュリティーと炎上リスクについてちゃんと読みましょう

**業務委託契約者のみ**

- [x] 請求書を作成してみよう
- [x] あなたの月額報酬が100,000円だったとして、請求書を作成してみましょう。

以上のチェックリストのタスクを全部完了した場合「Close issue」を押しましょう
質問が発生した場合は　@Khamida-schemeverge をメンションして質問をこちらのissueに投稿お願いします。

**Comment by Khamida-schemeverge** [comment]
@ToshioMOCHIZUKI-schemeverge ,  Onboardingお疲れ様です！
開発環境のHoraiをダウンロードが出来たら、こちらのissueを「Close」でお願いします。
