### ISSUE TITLE
望月さんのOnboarding Day 1 Checklist 【Corporate 担当者】

### ISSUE THREAD

**Issue by Khamida-schemeverge** [scheme-verge-inc/Onboarding#19]
- [x]  Onboarding_day1のアシスト(#100でスレッドを立てる、Onboardingの課題をコメントとして投稿する)
- [x] の挨拶とDay1の流れの説明
- [x] GitHubのログインをアシストする。
**GitHubのニックネームについて：**
      > 基本的に新しく作る方に名字と名前
      > 同じ名前や名字の人がいた場合も、ニックネームではなく名前の後ろに数字や単語をつけるなどで対応する　(例：yamadatarou-schemeverge）
      > Engineerなど既にアカウントを持っている人はニックネームでも許す

- [x] アカウントを作成したら、必ず新規メンバーを [write]アクセス権限でレポジトリーにインバイトしてください。（しないと、本人チェックリストをいじれない）

scheme-verge-inc→Onboarding→settings→Collaborators and Teams

- [x]  scheme vergeのWelcome Kitを渡す
- [x]  1日の終わりに新入社員と振り返りをする
- [x]  本人が持っている端末iOSかAndroidか確認して、フジコさんにテストフライトの招待を依頼する
