### ISSUE TITLE
椎名さんOnboarding Day 1 Checklist【本人】

### ISSUE THREAD

**Issue by Khamida-schemeverge** [scheme-verge-inc/Onboarding#25]
**👋scheme verge Onboardingへようこそ！👋**
まず、scheme verge のOnboardingの大まかな流れを[こちらのタイムライン](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)から確認しましょう。アサインされたのチェックリストとチェックリストの締め切りに従って、Onboardingを進めてください。

Onboardingの流れ

①招待通知
@schemeverge.com メールから通知が来たら、URLを踏んでscheme verge onboardingを見えるようになります。
②アクセス方法
scheme verge inc →Onboarding → Projects → scheme verge onboarding。
scheme verge onboarding プロジェクトを開いたら、今後より簡単なアクセスをできるようにこのページをブックマークとして保存してください。
③自分に割り当てられたタスクを確認してください。
④タスクに取り組み始めたら、[to-do] から [in progress] に移動することを忘れないでください。
⑤onboardingのどの部分にいるかに応じてタスクを開き、完了するまでタスクのチェックを開始してください。 リスト上のすべてのタスクが終了したら、[閉じる] を押します。他にタスクの進捗を報告する必要はありません。

❗️質問やコメントがある場合は、@[khamida.malianchinova@schemeverge.com](mailto:khamida.malianchinova@schemeverge.com) をメンションするタスク フィールドの下にコメントしてください。
❗️誤りや提案を見つけた場合は、Slack でご連絡ください。Onboardingを進めて、以下のto-doを完了させましょう。

**完了したら右のチェックボックストにチェックを入れてください。**

- [ ] [Handbook](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)の使い方を確認しよう
- [ ]  [Handbook](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)の検索をしよう
- [ ]  Google Driveに[scheme_verge_all]フォルダを追加しよう

**Slackを使いこなそう**
プロフィールを設定しよう

- [ ] プロフィール写真をアップロードしょう
- [ ] timesを作成しよう
- [ ] timesに田中さん（Kazuya Tanaka）、嶂南さん（Tatsuki Yamanami）、コーポレートメンバー（Khamida, Shiina Yamashita）と部門メンバーを追加しよう
- [ ] ppl_noticeに挨拶を投稿しよう
- [ ] 気になるtimes・サークルチャンネルに参加してみよう
- [ ] GitHubとSlackの連携しよう

規則のタスク
- [ ] 情報セキュリティーと炎上リスクについてちゃんと読みましょう

 AHMのタスク  
- [ ] AHMの直近過去2回分を視聴しよう
- [ ] AHMと懇親会の参加をカレンダーで返事しよう

**カレンダーを使いこなそう**

- [ ] 予定をセットし、__さんをインバイトしよう
- [ ] 田中さん・志方さんのカレンダーの使い方を確認しましょう。
- [ ] キャンセル・リスケしてみよう
- [ ]  稼働時間を表記しよう
- [ ] 他の人のカレンダーを見れるように設定しましょう
- [ ] Googleカレンダーの予定を他の人でも変更/編集できるように設定しよう
- [ ] [よくコミュニケーションするそうメンバーのスケジュールを見るように設定しましょう]((https://www.infact1.co.jp/staff_blog/webmarketing/47276/)    )
- [ ] Onboarding最初週、最初月のヒアリング招待を確認しよう

- [ ] メール署名の設定をしよう
- [ ] zoomの設定方法を確認しましょう。

**アプリダウンロードタスク**
- [ ] HoraiアプリをApp Storeや、Play Market からダウンロードしよう
- [ ] [こちらのスプシ](https://docs.google.com/spreadsheets/u/0/d/1G0dgMSk-ZZQG9NtNtLzveC7VM_8PeWUjCUUs3ocRJ08/edit)に名前とメールアドレスを入力しよう
**A欄に入力不要です**
- [ ] HubSpotの招待を確認しよう
- [ ] Handbookの写真・スキルと趣味は入れてるかどうか確認
- [ ] Facebookアカウントを作成しよう 
**※Facebookの[2段階認証はセキュリティ](https://ja-jp.facebook.com/help/148233965247823)上必須設定にしてください。**
- [ ] 開発環境のHoraiをダウンロードしよう

**iOSの場合は→　当日Apple IDを採用担当者に教えていただきます。その後フジコさんからインバイトが来て、そのインバイトを開いた後、ログインを進めてください。最後に、iPhoneにTestFlightをDLしてもらう。しばらくするとTestFlightにテスト用アプリが表示されるので、このアプリをダウンロード。**

**iOSの場合は →　schemeverge.comのメールにテストアプリをDLするURLをご案内する流れになります。**

- [ ] スマホmessengerをインストールし、使い来なそう
- [ ] PCのスペックについて確認

**業務委託契約者のみ**

- [ ] 請求書を作成してみよう
- [ ] あなたの月額報酬が100,000円だったとして、請求書を作成してみましょう。

以上のチェックリストのタスクを全部完了した場合「Close issue」を押しましょう
質問が発生した場合は　@Khamida-schemeverge をメンションして質問をこちらのissueに投稿お願いします。
