### ISSUE TITLE
2.EtiさんOnboarding Day 1 Checklist 【Corporate 担当者】

### ISSUE THREAD

**Issue by Khamida-schemeverge** [scheme-verge-inc/Onboarding#57]
- [ ]  Onboarding_day1のアシスト(#100でスレッドを立てる、Onboardingの課題をコメントとして投稿する)
- [ ] の挨拶とDay1の流れの説明
- [ ] GitHubのログインをアシストする。
- [ ] 雇用契約者の参加必須チャンネルにインバイトする

- [ ] Slackについて説明する
https://docs.google.com/document/d/11IDSYD662SO5VqwRmKoJ40qD34bZ49JwiG4Zs4rQ26Y/edit#bookmark=id.qax5176fsws4

910
911

**GitHubのニックネームについて：**
      > 基本的に新しく作る方に名字と名前
      > 同じ名前や名字の人がいた場合も、ニックネームではなく名前の後ろに数字や単語をつけるなどで対応する　(例：yamadatarou-schemeverge）
      > Engineerなど既にアカウントを持っている人はニックネームでも許す

- [ ] アカウントを作成したら、必ず新規メンバーを [write]アクセス権限でレポジトリーにインバイトしてください。（しないと、本人チェックリストをいじれない）

scheme-verge-inc→Onboarding→settings→Collaborators and Teams

- [ ]  本人を【社内／meet／Onboarding最初週のヒアリング】にGoogleカレンダーに招待する
**カレンダーのメッセージフォマート**

	<sub>○○さん、scheme vergeで最初の一一週間の勤務お疲れ様です！
その間Bizdevの業務に慣れられましたのでしょうか？今回も是非○○さんの最初の一週間に発生している不明点や不安・提案などについて聞くためにヒアリングを設定させていただきます。
よろしくお願いします。 </sub>

- [ ]  本人を【社内／meet／Onboarding最初月のヒアリング】にGoogleカレンダーに招待する

**カレンダーのメッセージフォマート**
	<sub>○○さん、scheme vergeで最初の一か月の勤務お疲れ様です！
その間Bizdevの業務に慣れられましたのでしょうか？今回も是非○○さんの最初の一週間に発生している不明点や不安・提案などについて聞くためにヒアリングを設定させていただきます。
よろしくお願いします。 </sub>

- [ ]  1日の終わりに新入社員と振り返りをする
- [ ]  本人が持っている端末iOSかAndroidか確認して、フジコさんにテストフライトの招待を依頼する
