### ISSUE TITLE
2Yu-JuさんOnboarding Day 1 Checklist 【Corporate 担当者】

### ISSUE THREAD

**Issue by Khamida-schemeverge** [scheme-verge-inc/Onboarding#67]
- [ ]  Onboarding_day1のアシスト(#100でスレッドを立てる、Onboardingの課題をコメントとして投稿する)
- [ ] の挨拶とDay1の流れの説明
- [ ] GitHubのログインをアシストする。
- [ ] 雇用契約者の参加必須チャンネルにインバイトする
910
911

**GitHubのニックネームについて：**
      > 基本的に新しく作る方に名字と名前
      > 同じ名前や名字の人がいた場合も、ニックネームではなく名前の後ろに数字や単語をつけるなどで対応する　(例：yamadatarou-schemeverge）
      > Engineerなど既にアカウントを持っている人はニックネームでも許す

- [ ] アカウントを作成したら、必ず新規メンバーを [write]アクセス権限でレポジトリーにインバイトしてください。（しないと、本人チェックリストをいじれない）

scheme-verge-inc→Onboarding→settings→Collaborators and Teams

- [ ]  本人を【社内／meet／Onboarding最初週のヒアリング】にGoogleカレンダーに招待する
**カレンダーのメッセージフォマート**

	<sub>○○さん、scheme vergeで最初の一一週間の勤務お疲れ様です！
その間Bizdevの業務に慣れられましたのでしょうか？今回も是非○○さんの最初の一週間に発生している不明点や不安・提案などについて聞くためにヒアリングを設定させていただきます。
よろしくお願いします。 </sub>

- [ ]  本人を【社内／meet／Onboarding最初月のヒアリング】にGoogleカレンダーに招待する

**カレンダーのメッセージフォマート**
	<sub>○○さん、scheme vergeで最初の一か月の勤務お疲れ様です！
その間Bizdevの業務に慣れられましたのでしょうか？今回も是非○○さんの最初の一週間に発生している不明点や不安・提案などについて聞くためにヒアリングを設定させていただきます。
よろしくお願いします。 </sub>

- [ ]  1日の終わりに新入社員と振り返りをする
- [ ]  本人が持っている端末iOSかAndroidか確認して、フジコさんにテストフライトの招待を依頼する

**Androidの場合は** 
 登録するテストユーザーのアドレス（Gアカウント）
登録するテストユーザーの名前：

1:[Google play Console](https://accounts.google.com/ServiceLogin?service=androiddeveloper&passive=true&continue=https%3A%2F%2Fplay.google.com%2Fconsole%2Fdeveloper%2F&_ga=2.129672719.242788295.1637566541-1871471452.1637566541)にログインする

2：「すべてのアプリ」からテスターになってもらうアプリを選択する

3：ダッシュボードから「テスト」＞「内部テスト」＞「テスター数」で「horai」を選択

4：「メーリングリストの編集」画面で「メールアドレスの追加」にテスターのGアカウントを入力し、保存する。

5：「内部テスト」の画面にもどり「テストへの参加方法」にある「リンクをコピー」をクリックして
リンクURLをテスターへ連絡する

**iOSの場合は** 
## Information
- 氏名・name: 
- email: ※使用するiphoneの AppleID 
- Applicable apps
  - [ ] horai（開発用）
  - [ ] setogei

## 手順
 1：[App Store Connect](https://appstoreconnect.apple.com/)にログインする
 2：ユーザとアクセスにて新規ユーザを登録する
<img width="1621" alt="スクリーンショット 2022-03-03 12 10 16" src="https://user-images.githubusercontent.com/77137461/156488986-95645d8e-9fd3-48b4-a105-a734096f16d6.png">

<img width="1305" alt="スクリーンショット 2022-03-03 12 12 34" src="https://user-images.githubusercontent.com/77137461/156489759-2dca0290-99c2-4d40-aff3-827ba7d7d2c5.png">

 
 3：Appにてテストしてもらうアプリを選択する
<img width="1423" alt="スクリーンショット 2022-03-03 12 21 12" src="https://user-images.githubusercontent.com/77137461/156489951-c75d83b0-5256-425c-9602-b98e6fe9ef29.png">

 
 4：アプリの画面にて「TestFlight」＞「内部テスト」＞「テスター」でユーザーを選択する
<img width="1387" alt="スクリーンショット 2022-03-03 12 23 01" src="https://user-images.githubusercontent.com/77137461/156490656-504ef3ea-c536-4069-8dfa-ce35c9a9a40d.png">

 
 5：ユーザーのiPhoneにTestFlightをDLしてもらう。しばらくするとTestFlightにテスト用アプリが表示される

- [ ]新規メンバーを全てツールに招待後、ツールチェックリストを正確にアップデートする
https://docs.google.com/spreadsheets/d/1KbjNJk7pkFydtPxXTK7frTJKyRZ8VKl-WUJ1GCnO-Xo/edit#gid=794106033
