### ISSUE TITLE
2.浅川さんOnboarding Day 1 Checklist【本人】

### ISSUE THREAD

**Issue by Khamida-schemeverge** [scheme-verge-inc/Onboarding#70]
**👋scheme verge Onboardingへようこそ！👋**
まず、scheme verge のOnboardingの大まかな流れを[こちらのタイムライン](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)から確認しましょう。アサインされたのチェックリストとチェックリストの締め切りに従って、Onboardingを進めてください。

Onboardingの流れ

①招待通知
@schemeverge.com メールから通知が来たら、URLを踏んでscheme verge onboardingを見えるようになります。
②アクセス方法
scheme verge inc →Onboarding → Projects → scheme verge onboarding。
scheme verge onboarding プロジェクトを開いたら、今後より簡単なアクセスをできるようにこのページをブックマークとして保存してください。
③自分に割り当てられたタスクを確認してください。
④タスクに取り組み始めたら、[to-do] から [in progress] に移動することを忘れないでください。
⑤onboardingのどの部分にいるかに応じてタスクを開き、完了するまでタスクのチェックを開始してください。 リスト上のすべてのタスクが終了したら、[閉じる] を押します。他にタスクの進捗を報告する必要はありません。

❗️質問やコメントがある場合は、@[khamida.malianchinova@schemeverge.com](mailto:khamida.malianchinova@schemeverge.com) をメンションするタスク フィールドの下にコメントしてください。
❗️誤りや提案を見つけた場合は、Slack でご連絡ください。Onboardingを進めて、以下のto-doを完了させましょう。

**完了したら右のチェックボックストにチェックを入れてください。**

- [x]  Githubのアクセスをすぐできるようにタスクのviewをブックマークしよう
- [x] [Handbook](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)の使い方を確認しよう
- [x]  [Handbook](https://sites.google.com/schemeverge.com/scheme-verge-wiki/onboarding)の検索をしよう
- [x]  Google Driveに[scheme_verge_all](https://drive.google.com/drive/folders/1jml8WRT87e_NaUOPf9sM88Q90OSHr6_d)フォルダを追加しよう

**Slackを使いこなそう**
プロフィールを設定しよう

- [x] プロフィール写真をアップロードしょう
- [x] timesを作成しよう
- [x] timesに田中さん（Kazuya Tanaka）、嶂南さん（Tatsuki Yamanami）、コーポレートメンバー（Khamida, Shiina Yamashita）と部門メンバーを追加しよう
- [x] ppl_noticeに挨拶を投稿しよう
- [x] 気になるtimes・サークルチャンネルに参加してみよう
- [x] GitHubとSlackの連携しよう

規則のタスク
- [x] 情報セキュリティーと炎上リスクについてちゃんと読みましょう

 AHMのタスク  
- [x] AHMの直近過去1回分を視聴しよう
- [x] AHMと懇親会の参加をカレンダーで返事しよう

**[カレンダーを使いこなそう](https://sites.google.com/schemeverge.com/scheme-verge-wiki/departments/corporate-department/%E7%B7%8F%E5%8B%99/google-%E3%82%AB%E3%83%AC%E3%83%B3%E3%83%80%E3%83%BC%E3%81%AE%E7%A2%BA%E8%AA%8D%E6%8B%9B%E5%BE%85%E6%96%B9%E6%B3%95)**

- [x] 田中さんのカレンダーの使い方を確認しましょう。
- [x] キャンセル・リスケしてみよう
- [x]  稼働時間を表記しよう
- [x] 他の人のカレンダーを見れるように設定しましょう
- [x] Googleカレンダーの予定を他の人でも変更/編集できるように設定しよう
- [x] [よくコミュニケーションするそうメンバーのスケジュールを見るように設定しましょう]((https://www.infact1.co.jp/staff_blog/webmarketing/47276/)    )

- [x] メール署名の設定をしよう
- [x] スマホmessengerをインストールし、使い来なそう
- [x] 「嶂南」さんの漢字変換の登録してください。

以上のチェックリストのタスクを全部完了した場合「Close issue」を押しましょう
質問が発生した場合は　@Khamida-schemeverge をメンションして質問をこちらのissueに投稿お願いします。
